### ISSUE TITLE
Rebuild 2018.01

### ISSUE THREAD

**Issue by kellrott** [biostream/bmeg-etl#20]
- [ ] `protograph/ccle/ccle.Biosample.Vertex.json` BioSamples have wrong gid (`u'vertex': {u'gid': u'biosample::', u'data': {u'_label': u'Biosample', u'source': u'ATCC', ...`)
- [ ] New schema has ResponseCurve being created a vertex, rather then edge
- [ ] Inconsistent ids used in different response curve records. In `protograph/ctdd/ctdd.ResponseCurve.Edge.json` it is `"from":"ccle:CAKI2_KIDNEY"` and in `protograph/ccle/ccle.ResponseCurve.Edge.json` it is `biosample:CCLE:CAKI2_KIDNEY`
- [ ] `protograph/mc3/mc3.VariantAnnotation.Edge.json` has nothing by `"to":"gene:0"`
- [ ] No edge connecting Variant to Callset
- [ ] MC3 Convert Incorrect https://github.com/biostream/bmeg-etl/issues/19

Missing Elements:
- [x] CCLE variants
- [ ] CCLE expression data
- [ ] GDC build
- [x] Ensembl Transcript and Exon vertices missing
- [ ] PubChem extractor

**Comment by prismofeverything** [comment]
I went to compare the CCLE samples to the TCGA ones to see how they differ (since the Biosample protograph is tailored to the TCGA samples), and see we don't have the TCGA samples up there. What process is supposed to generate those?

Just looking at the CCLE sample entries though they seem very different from the TCGA ones. Perhaps we need a `ccle.Biosample` entry to distinguish them.

**Comment by prismofeverything** [comment]
Looks like the CCLE expression data is not in the biostream.... where is that supposed to come from?

**Comment by kellrott** [comment]
For the GDC Biospecimen data, you need to run the converter
Process:
```
    - key: gdc-biospecimen-transform
      command: gdc-biospecimen-transform
      inputs:
        TARBALL: BIOSAMPLE_ARCHIVE
      outputs:
        BIOSAMPLE: BIOSAMPLE
```

Command:
```
- key: gdc-biospecimen-transform
  image: biostream/gdc-transform
  command: ["python", "/opt/convert-clinical.py", "--tar", "/in/tarball.tar", "--out", "/out/"]
  inputs:
    TARBALL: /in/tarball.tar
  outputs:
    BIOSAMPLE: /out/tcga.Biosample.json
```
